### ISSUE TITLE
Feed validation problems

### ISSUE THREAD

**Issue by aribn** [snarfed/twitter-atom#5]
The feed returned for Twitter list `aribadernatal/my-tweets` has validation errors, preventing it being usable by [FeedWordPress](https://wordpress.org/plugins/feedwordpress/). 

The line that seems to responsible the error (according to the [W3C feed validation service](https://validator.w3.org/feed/)) contains an unescaped closing quote mark (`’`), which might be the culprit.

**Comment by snarfed** [comment]
thanks for the report! looking now.

**Comment by snarfed** [comment]
should be fixed now. thanks again for the report!

**Comment by aribn** [comment]
Thank you for taking the time to track this down! I'm looking forward to using it.
