### ISSUE TITLE
img Unexpected close tag

### ISSUE THREAD

**Issue by lqzhgood** [snarfed/twitter-atom#9]
linke this url 
`http://notepad.live/club0 `

990 line  img tag

**Comment by snarfed** [comment]
thanks for reporting! fixed. related to https://github.com/snarfed/instagram-atom/issues/3#issuecomment-350205685, snarfed/granary#93.

(i've also removed the link in your report since it has your access token.)

**Comment by lqzhgood** [comment]
Amazing !
I just finished writing a regex to hack this bug, ready to test the discovery has been fixed.
You're too fast, thank you
